### PR TITLE
Revert "MUST NOT use GitHub secrets"

### PR DESCRIPTION
**Pull request by MrAlias**
Reverts signalfx/gdi-specification#186

This does not look to have had consensus across implementations.

_Based on comment originally posted by @breedx-splk in https://github.com/signalfx/gdi-specification/issues/186#issuecomment-1234431840_

### CODE REVIEW

**Review by pellared — CHANGES_REQUESTED** [review]
This change comes from the internal GDI Security doc which is valid for a quite long time.

**Comment by MrAlias** [comment]
> This change comes from the internal GDI Security doc which is valid for a quite long time.
> 
> EDIT: I created #189

Please see the linked comment. The PR was merged in error, there was not a consensus across implementations.

I am not opening this PR to address the normative standards of the specification. I am opening it to affect procedural change. If you would like to still submit those changes, please do so after this is merged and please wait to merge those possible changes  util community consensus is reached.

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by pellared** [comment]
@MrAlias AFAIK this req is not about "community consensus" but it was requested by our internal sec team (it is a constraint for us).

@emaderer Can you please here? Maybe I am wrong.

**Comment by MrAlias** [comment]
> @MrAlias AFAIK this req is not about "community consensus" but it was requested by our internal sec team (it is a constraint for us).
> 
> @emaderer Can you please help here? Maybe I am wrong.

Again, I'm not debating the merits of the change made in #186. This PR reverts changes that were made in that PR without community consensus:



If the underlying changes need to ultimately be included in the specification or not is for another issue/PR to discuss. This PR is to revert changes that should not have been made.  I'm not sure why there is a debate here.

**Review by pellared — APPROVED** [review]

**Pull request merged**
