### PR TITLE
Update instrumentation specification

### PR DESCRIPTION
**Pull request by flands**
- Mostly refactoring of existing language.
- Mark RUM and serverless experimental

### CODE REVIEW

**Comment by pellared** [comment]
> Mark RUM and serverless experimental

Can you please briefly explain it? Asking because it is already "marked" as stable: https://github.com/signalfx/gdi-specification/blob/v1.1.0/specification/configuration.md

**Comment by flands** [comment]
> > Mark RUM and serverless experimental
> 
> Can you please briefly explain it? Asking because it is already "marked" as stable: https://github.com/signalfx/gdi-specification/blob/v1.1.0/specification/configuration.md

Definitely! The serverless spec was just merged -- it is not fully implemented and is not really used/tested externally yet. How can it be stable? This was missed during review (at least by me). RUM may be more contentious -- perhaps feature-freeze would be a better state.

**Review by pellared — APPROVED** [review]
It may be worth making a release after this PR is merged.

**Review by MrAlias — APPROVED** [review]
Can you add an entry in the CHANGELOG clarifying the stability of the RUM and serverless configuration components as a bug fix?

**Pull request merged**
